apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front-service
  namespace: default
spec:
  selector:
    app: azure-vote-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Crea un LoadBalancer en Azure
