all:
  hosts:
    vm:
      ansible_host: 52.174.181.21  # Reemplaza con la IP de tu VM en Azure
      ansible_user: adminuser  # Usuario de la VM
      ansible_ssh_private_key_file: ~/.ssh/id_rsa # Ruta a la clave privada

    localhost:
      ansible_connection: local  # Para ejecutar tareas en la máquina local

  children:
    acr:
      hosts:
        localhost

    webserver:
      hosts:
        vm

  vars:
    acr_name: dpbCP2acr3b2f
    acr_registry: "{{ acr_name }}.azurecr.io"  # Definimos el registro de ACR
    ansible_python_interpreter: /usr/bin/python3  # Asegura que Ansible use Python 3
