all:
  hosts:
    vm:
      ansible_host: XX.XXX.XXX.XX  
      ansible_user: adminuser
      ansible_ssh_private_key_file: ~/.ssh/id_rsa # Ruta a la clave privada

    localhost:
      ansible_connection: local 

  children:
    acr:
      hosts:
        localhost

    webserver:
      hosts:
        vm

  vars:
    acr_name: dpbCP2ac5454fswedsda
    acr_registry: "{{ acr_name }}.azurecr.io"
    ansible_python_interpreter: /usr/bin/python3
