- name: ACR and Apps
  hosts: localhost
  connection: local
  vars_files:
    - secrets.yml
  vars:
    app_namespace: "namespaceKubernetes"
    kube_config_path: "/mnt/c/Users/.../.kube/config"
  become: true
  roles:
    - acr
    - vm
    - aks


